name: chat_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_launcher_icons: ^0.13.0

  # For integrating firebase
  firebase_core: ^2.7.1 
  
  # For handing firebase authendicaton
  firebase_auth: ^4.2.10
  
  # For handling google sign in
  google_sign_in: ^6.0.2
  
  # For accessing cloud firestore database
  cloud_firestore: ^4.4.4
  
  # For showing network images(email profile pic in avatar image)
  cached_network_image: ^3.2.3
  
  # For adding avg files
  flutter_svg: ^2.0.4
  
  # For picking images from gallery
  image_picker: ^0.8.7+1
  
  # For acessing FIrebase Storage(for uploading files) 
  firebase_storage: ^11.1.0
  
  # For showing Emojis😊
  emoji_picker_flutter: ^1.5.4
  
  # for accessing firebase messaging (push notifications)
  firebase_messaging: ^14.4.1
  
  # (REST) API (Application Programming Interface)
  # simply helps our app to communicate oe share data with server through URl methods like GET/POST etc
  # For calling REST API
  http: ^0.13.5
  
  # For creating notification channel
  flutter_notification_channel: ^2.0.0
  
  # For saving images into gallery
  gallery_saver: ^2.3.2
  

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/app_icon1.png"
  min_sdk_android: 21

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icons/

 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

